"""Rename expires_at column

Revision ID: 6cda05b826ee
Revises: 19c2e5cbbc1e
Create Date: 2025-06-28 19:04:20.274593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cda05b826ee'
down_revision: Union[str, Sequence[str], None] = '19c2e5cbbc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guildmember')
    op.drop_table('oauthtoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('oauthtoken_pkey'))
    )
    op.create_table('guildmember',
    sa.Column('character_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('realm', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('race', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clazz', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('faction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('character_id', name=op.f('guildmember_pkey'))
    )
    # ### end Alembic commands ###
